In [1]:
import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt

In [2]:
image = cv2.imread('C:/Users/sriji/MachineLearning/DemoDatasets/Lesson 7/tiger.png')

In [3]:
print(type(image))

<class 'numpy.ndarray'>


In [4]:
image.shape

(720, 1280, 3)

In [5]:
img = image.reshape((-1,3))

In [6]:
img.dtype

dtype('uint8')

# change the data type from uint8 to float32, only then we can use in KMeans
# refer documentaion of openCV

In [7]:
img = np.float32(img)

In [8]:
img.dtype

dtype('float32')

In [9]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)

#max iterations = 10 and epsilon = 1.0

In [10]:
k = 6

In [11]:
attempts = 10

In [12]:
ret,label,center=cv2.kmeans(img,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)

In [13]:
print(center)

[[ 93.919365 111.49148  117.054085]
 [170.97664  175.53699  180.44131 ]
 [ 26.54683   30.19475   37.67025 ]
 [129.62569  142.57086  156.35716 ]
 [ 56.224415  82.65589   78.458855]
 [213.93181  215.03865  217.32912 ]]


In [14]:
print(type(center))

<class 'numpy.ndarray'>


In [15]:
center = np.uint8(center)

In [16]:
res = center[label.flatten()]

In [17]:
res

array([[170, 175, 180],
       [170, 175, 180],
       [170, 175, 180],
       ...,
       [ 93, 111, 117],
       [ 93, 111, 117],
       [ 93, 111, 117]], dtype=uint8)

In [18]:
res.shape

(921600, 3)

In [19]:
res2 = res.reshape((image.shape))

In [20]:
res2.shape

(720, 1280, 3)

In [21]:
cv2.imwrite('segmented.png',res2)

True