In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split as tts

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
print(type(iris))

<class 'sklearn.utils.Bunch'>


In [5]:
X = iris.data[:,:2]

y = iris.target

In [6]:
logreg = LogisticRegression()

In [7]:
X_train,X_test,y_train,y_test = tts(X,y,test_size=0.3)

In [8]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(105, 2) (45, 2) (105,) (45,)


In [9]:
logreg.fit(X_train,y_train)

D:\Software-Installation\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Software-Installation\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [10]:
y_pred = logreg.predict(X_test)

In [11]:
logreg.intercept_

array([ 0.48254212,  0.73854057, -1.36696094])

In [12]:
logreg.coef_

array([[-2.26398388,  3.7145    ],
       [ 0.60685992, -1.66862103],
       [ 1.00638387, -1.77727222]])

In [13]:
print("Classifiation Report")

print(classification_report(y_test,y_pred))

Classifiation Report
              precision    recall  f1-score   support

           0       0.85      0.92      0.88        12
           1       0.70      0.47      0.56        15
           2       0.73      0.89      0.80        18

    accuracy                           0.76        45
   macro avg       0.76      0.76      0.75        45
weighted avg       0.75      0.76      0.74        45



In [14]:
print("Confusion Matrix")

print(confusion_matrix(y_test,y_pred))

Confusion Matrix
[[11  1  0]
 [ 2  7  6]
 [ 0  2 16]]
